AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  InitRoleLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess
      Path: /
  TestSAM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sendGridTutorial
      Role: !GetAtt [InitRoleLambda, Arn]
      Runtime: provided
      Layers:
        - arn:aws:lambda:xx-xxxx-x:xxxxxxxxxxxx:layer:xxx-runtime-layer:x
      CodeUri: ./src
      Description: TEST SAM
      MemorySize: 1024
      Timeout: 15
  createS3:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: PublicRead
